"use client"

import type { Metadata } from "next";

import "./globals.scss";
import { useState } from "react";
import { darkTheme, lightTheme } from "./theme/theme";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isDark, setIsDark] = useState(false)
  const switchTheme: any = ()  => {
      setIsDark(!isDark)
  }
      
  
  return ( 
    <html lang="en">
      <ThemeProvider theme={isDark ? darkTheme : lightTheme}>
        <LocalizationProvider dateAdapter={AdapterDayjs}>
          <CssBaseline/>
          <body >{children}</body>
        </LocalizationProvider>
      </ThemeProvider>
    </html>
  );
}
